name: Coverage

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Setup
        uses: ./.github/actions/setup
      - name: Install Playwright Browsers
        uses: ./.github/actions/playwright-browser-install
      - name: Test
        run: pnpm test
      - uses: qltysh/qlty-action/coverage@v2
        with:
          token: ${{secrets.QLTY_COVERAGE_TOKEN}}
          files: coverage/lcov.info